name: Atualizar CSV com Web Scraping

on:
  schedule:
    - cron: '0 3 * * *'  # Roda todos os dias às 03:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt  # Certifique-se de que tem este arquivo no repositório

      - name: Rodar o script de web scraping
        run: python webscrapping_dash_githubactions.py

      - name: Commitar e enviar o CSV atualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add nivel_dos_rios.csv
          git commit -m "Atualização automática do CSV"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
