name: Atualizar CSV com Web Scraping

on:
  schedule:
    - cron: '0 3 * * *'  # Roda todos os dias às 03:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip python3-venv python3-pip
          
      - name: Instalar Google Chrome e ChromeDriver
        run: |
          # Remover qualquer versão anterior do Google Chrome para evitar conflitos
          sudo apt-get remove -y google-chrome-stable

          # Instalar dependências necessárias para o Google Chrome
          sudo apt-get install -y libxss1 libappindicator3-1 libindicator7

          # Baixar e instalar o Google Chrome
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y  # Corrige dependências faltantes

          # Forçar a instalação das dependências
          sudo apt-get install -f -y

          # Baixar e instalar o ChromeDriver compatível com a versão do Google Chrome
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9.]+' | head -1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verificar as versões do Chrome e do ChromeDriver
          google-chrome --version
          chromedriver --version

      - name: Configurar Python e instalar dependências
        run: |
          python -m venv venv  # Criar ambiente virtual
          source venv/bin/activate
          pip install --upgrade pip
          
          # Instalar dependências do projeto
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas beautifulsoup4 selenium
          fi
          
          # Verificar se as dependências foram instaladas corretamente
          pip list

      - name: Rodar o script de web scraping
        run: |
          source venv/bin/activate
          which python  # Verifica se o Python do venv está ativado
          python webscrapping_dash_githubactions.py

      - name: Commitar e enviar o CSV atualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add nivel_dos_rios.csv
          
          # Verifica se há mudanças antes de tentar commitar
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada no CSV. Saindo..."
            exit 0
          fi

          git commit -m "Atualização automática do CSV"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
