name: Atualizar CSV com Web Scraping

on:
  schedule:
    - cron: '0 3 * * *'  # Roda todos os dias às 03:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Corrigir pacotes quebrados antes da instalação do Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo apt-get install -f -y  # Corrigir pacotes pendentes
          
          # Baixar e instalar o Chrome
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
          
          google-chrome --version    


      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          
          # Baixar o Google Chrome
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          
          # Instalar o Chrome e corrigir dependências quebradas
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
          
          # Verificar se o Chrome foi instalado corretamente
          google-chrome --version


      - name: Configurar Python e instalar dependências
        run: |
          python -m venv venv  # Cria um ambiente virtual
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || pip install pandas beautifulsoup4 selenium

      - name: Rodar o script de web scraping
        run: |
          source venv/bin/activate
          python webscrapping_dash_githubactions.py

      - name: Commitar e enviar o CSV atualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add nivel_dos_rios.csv
          
          # Verifica se há mudanças antes de tentar commitar
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada no CSV. Saindo."
            exit 0
          fi

          git commit -m "Atualização automática do CSV"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
